services:
  - type: web
    name: med-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0 